name: Deploy to Netlify

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.11.1'  # Adjust the Node.js version as per your requirements

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install Dependencies
        run: |
          cd portfolio-react  # Navigate into your portfolio-react folder
          npm install         # Install the dependencies

      - name: Build the Project
        run: |
          cd portfolio-react  # Navigate into your portfolio-react folder
          npm run build       # Build the project

      - name: Check Build Folder
        run: |
          cd portfolio-react
          ls -alh dist  # Verify the contents of the dist folder

      - name: Install Netlify CLI
        run: npm install -g netlify-cli  # Install the Netlify CLI globally

      - name: Deploy to Netlify
        run: |
          cd portfolio-react  # Navigate into your portfolio-react folder
          netlify deploy --prod --dir=./dist  # Deploy the dist folder to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
